### Params
@baseURL = http://localhost:7071/api
//@baseURL = https://fnapp4team10.azurewebsites.net/api


@userId = cc20a6fb-a91f-4192-874d-132493685376
@ratingId = 2329fd7b-3491-4949-9111-9fb3f5093d2d


### URLs
@createRatingURL = {{baseURL}}/rating
@getRatingsURL = {{baseURL}}/ratings?userId={{userId}}
@getRatingURL = {{baseURL}}/rating/{{ratingId}}


### Create sample rating
POST {{createRatingURL}}

{
  "userId": "cc20a6fb-a91f-4192-874d-132493685376",
  "productId": "4c25613a-a3c2-4ef3-8e02-9c335eb23204",
  "locationName": "Sample ice cream shop2",
  "rating": 5,
  "userNotes": "I love the subtle notes of orange in this ice cream!222"
}


### Get all ratings by userId
GET {{getRatingsURL}}


### Get single rating
GET {{getRatingURL}}
