### Params
//@baseURL = http://localhost:7071/api
@baseURL = https://team10apim.azure-api.net

### Mobile Subscription Key
@ocpApimSubscriptionKey =

### Internal Subscription Key
//@ocpApimSubscriptionKey =

### Esternal Subscription Key
//@ocpApimSubscriptionKey =

@userId = cc20a6fb-a91f-4192-874d-132493685376
@ratingId = a528af35-1579-4e89-a173-f25d2e4d9a3d

@productId = 4c25613a-a3c2-4ef3-8e02-9c335eb23204

### URLs
@createRatingURL = {{baseURL}}/rating
@getRatingsURL = {{baseURL}}/ratings?userId={{userId}}
@getRatingURL = {{baseURL}}/ratings/{{ratingId}}

@getProductsURL = {{baseURL}}/products

@getProductURL = {{baseURL}}/products/{{productId}}


### Create sample rating
POST {{createRatingURL}}
ocp-apim-subscription-key: {{ocpApimSubscriptionKey}}

{
  "userId": "cc20a6fb-a91f-4192-874d-132493685376",
  "productId": "4c25613a-a3c2-4ef3-8e02-9c335eb23204",
  "locationName": "Sample ice cream shop2",
  "rating": 5,
  "userNotes": "I love the subtle notes of orange in this ice cream!222"
}


### Get all ratings by userId
GET {{getRatingsURL}}
ocp-apim-subscription-key: {{ocpApimSubscriptionKey}}

### Get single rating
GET {{getRatingURL}}
ocp-apim-subscription-key: {{ocpApimSubscriptionKey}}

### Get Products
GET {{getProductsURL}}
ocp-apim-subscription-key: {{ocpApimSubscriptionKey}}

### Get Product
GET {{getProductURL}}
ocp-apim-subscription-key: {{ocpApimSubscriptionKey}}
