name: Test and Deploy (Functions Action)

on: workflow_dispatch
  
env:
  AZURE_FUNCTION_NAME: fnapp4team10
  AZURE_FUNCTION_PROJ_PATH: .
  ROOT_SOLUTION_PATH: .

permissions:
  id-token: write
  contents: read
      
jobs: 
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
            client-id: ${{ secrets.AZURE_CLIENT_ID }}
            tenant-id: ${{ secrets.AZURE_TENANT_ID }}
            subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.100'
        
      - name: Restore dependencies
        run: dotnet restore


      - name: Build for Testing
        run: dotnet build --no-restore
      
      - name: Test
        run: dotnet test --no-build --verbosity normal
      
      - name: Build Function App for Release
        run: dotnet build --configuration Release --output ./output

      - name: 'Run Azure Functions Action'
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: ${{ env.AZURE_FUNCTION_NAME }}
          package: './output'