# File: .github/workflows/platform.yml
name: Deploy Azure Platform

on: workflow_dispatch

env:
  AZURE_RG_NAME: openhackapis
  AZURE_SUBSCRIPTION_ID: 'f6f8c9b0-0f67-4eac-a65f-6c3035e1bdb1'
  AZURE_FUNCTION_NAME: fnapp4team10

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
            client-id: ${{ secrets.AZURE_CLIENT_ID }}
            tenant-id: ${{ secrets.AZURE_TENANT_ID }}
            subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Create Resource Group
        uses: azure/arm-deploy@v1
        with:
          scope: subscription
          region: westeurope
          subscriptionId: ${{ env.AZURE_SUBSCRIPTION_ID }}
          template: ./deployPlatform/deployResourceGroup.json
          parameters:
            rgName="${{ env.AZURE_RG_NAME }}"
            location="westeurope"

      - name: Depoy Function Runtime
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ env.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: ${{ env.AZURE_RG_NAME }}
          template: ./deployPlatform/deployFunctionRuntime.json
          parameters:
            appName="${{ env.AZURE_FUNCTION_NAME }}"
